### ISSUE TITLE
Support auto-gen-config options

### ISSUE THREAD

**Issue by tos-miyake** [ryz310/rubocop_challenger#215]
please support 

auto-gen-config options :bow:

ex)
```
rubocop --auto-gen-config --exclude-limit 99999 --no-offense-counts --no-auto-gen-timestamp
```

**Comment by ryz310** [comment]
Hi, @tos-miyake 

I confirmed your request :)
It may be able to support options that `--exclude-limit` and `--no-auto-gen-timestamp`. 
But cannot support `--no-offense-counts` option because RubocopChallenger is using `offence count` value on choosing rules.

**Comment by ryz310** [comment]
ちなみに日本語でも大丈夫です 😉

**Comment by tos-miyake** [comment]
ありがとうございます:smile:

**Comment by ryz310** [comment]
@tos-miyake 

RubocopChallenger supported above features on #217 😁 
I will release the feature at next version, perhaps at v2.0.0.pre5.
It will be pre version so you need `--pre` option when installing gem.
i.e. `$ gem install rubocop_challenger --pre`

---
#217 で上記の機能を実装しました 😁 
`v2.0.0.pre5` でリリース予定ですが `pre` バージョンなので gem インストール時に `--pre` が必要になるのでご注意ください 🙏

**Comment by tos-miyake** [comment]
@ryz310 早い！ありがとうございます！感謝感謝！
