### ISSUE TITLE
not work auto-gen-config options when base branch option with use

### ISSUE THREAD

**Issue by tos-miyake** [ryz310/rubocop_challenger#222]
#215 で対応して頂いた変更なんですが、`--base=xxxx` optionと一緒に利用できないようです。

ex)
```
bundle exec rubocop_challenger go \
  --email=info@xxxx.com \
  --name="xxxx-bot" \
  --exclude-limit 99999 \
  --no-auto-gen-timestamp \
  --base=xxxx
```

error log
```
ERROR: "rubocop_challenger go" was called with arguments ["--base=xxxx"]
Usage: "rubocop_challenger go --email=EMAIL --name=NAME"
Exited with code 1
```

**Comment by tos-miyake** [comment]
`--base` optionがそもそもドキュメント(README)等にないので、勘違いしていた様です:bow:

**Comment by ryz310** [comment]
@tos-miyake 

ちなみに `--base` option を使ってどういう事を実現したかった感じですかね？
git で merge 先の branch 変えるとかですか？

**Comment by tos-miyake** [comment]
@ryz310 
> ちなみに --base option を使ってどういう事を実現したかった感じですかね？
> git で merge 先の branch 変えるとかですか？

そんな感じです！
デフォルトがdevelop branch向きで作成されるんだと勘違いしていたんだと思います。

もともと動作としては困っていなくて、間違ったoptionを渡して挙動が変わっていたと勘違いしていました。
version upの改修でinvalidなoptionを指定している場合にerrorになる改善が入って、
発覚したと認識しています。

わざわざレスしてくださってありがとうございます:smile:

**Comment by tos-miyake** [comment]
@ryz310 

お手すきで大丈夫なんですが、
staging branchで実行していて、
向き先がmaster branchへのpull requestになってしまいました。

向き先のbranchを指定するoptionって存在しますか？

circleci 抜粋
```
      - run:
          name: Rubocop Challenge
          command: |
            bundle install --path=vendor/bundle
            bundle exec rubocop_challenger go \
              --email=info@xxxx.com \
              --name="xxxx-bot" \
              --exclude-limit 99999 \
              --no-auto-gen-timestamp

~~~
  nightly:
    triggers:
      - schedule:
          cron: "30 23 * * 0,1,2,3,4"
          filters:
            branches:
              only:
                - staging
    jobs:
      - rubocop_challenge_job

```

**Comment by ryz310** [comment]
@tos-miyake 

現時点では用意してないですね。ただ、内部で扱ってる変数としては存在しているので、オプションとして用意する事は可能ですよ 👀時間取れたら対応しますね 👍 

https://github.com/ryz310/rubocop_challenger/blob/a0ac9528db42635284599ac25b16940c171d981b/lib/rubocop_challenger/pull_request.rb#L22-L28

**Comment by tos-miyake** [comment]
@ryz310 ありがとうございます:bow:

**Comment by ryz310** [comment]
@tos-miyake v2.0.0.pre6 で対応しました 👍 `--base-branch` で指定できます 🙏

**Comment by tos-miyake** [comment]
@ryz310 おぉ、ありがとうございます!
感謝！感謝！
