### ISSUE TITLE
Support --no-offense-counts .rubocop_todo.yml

### ISSUE THREAD

**Issue by r7kamura** [ryz310/rubocop_challenger#613]
The recent rubocop has `--no-offense-counts` option, that hides offences count from .rubocop_todo.yml for better diff management.

It seems that the current implementation doesn't support it because every rule that doesn't have `Offence count: ...`  section is considered as invalid and rejected.

https://github.com/ryz310/rubocop_challenger/blob/b290d859efc18e3fda14ff66dca768efc0d7df00/lib/rubocop_challenger/rubocop/todo_reader.rb#L61-L63

https://github.com/ryz310/rubocop_challenger/blob/b290d859efc18e3fda14ff66dca768efc0d7df00/lib/rubocop_challenger/rubocop/rule.rb#L49-L52

**Comment by ryz310** [comment]
Resolved by #616
