### ISSUE TITLE
Unrelated gems are installed and updated (and necessary gems might not be installed?)

### ISSUE THREAD

**Issue by r7kamura** [ryz310/rubocop_challenger#617]
When I tried to use rubocop_challenger in a large Rails application, several problems occured and it didn't work, so let me explain it here.

rubocop_challenger attempts to perform the following command:

```
bundle update \
  rubocop \
  rubocop-performance \
  rubocop-rails \
  rubocop-rake \
  rubocop-rspec \
  rubocop-thread_safety
```

but I think there are some problems in this process.

1. The target gems should not be determined arbitrarily, but rather based on which libraries are used in the application.
2. The update feature should be removed or made optional, since the normal user does not use this gem to update gems, but to improve .rubocop_todo.yml. (This is the main reason I finally decided not to use rubocop_challenger in this project)
3. Installing all the gems used in the application is very time consuming, so it should only install the gems necessary to run RuboCop. (as a workaround, I created `rubocop` gem group and set BUNDLE_WITHOUT=default,development,test,production)

For example, this is the .rubocop.yml in my application.

```yaml
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rails_deprecation
  - rubocop-rspec
  - empty_example_cop
  - ./lib/rubocop_rails_deprecation
```

When I run `rubocop_challenger go` in this environment, I get an error the first time it tried to regenerate .rubocop_todo.yml, and .rubocop_todo.yml is updated with empty string. The process doesn't stop there, and it tries to regenerate a second time and parse the empty .rubocop_todo.yml further, and an error occurs. This is the error described in the following comment.

https://github.com/ryz310/rubocop_challenger/pull/612#issuecomment-1125644922

**Comment by ryz310** [comment]
@r7kamura 
Hi!
Thank you for your valuable opinion. I wanted to know the execution examples in various Rails applications, so it's helpful.
But I could not understand some of your reports.

> 1. The target gems should not be determined arbitrarily, but rather based on which libraries are used in the application.

Rubocop challenger does not determine target gems arbitrarily, it verifies that target gems have been installed with `$ bundle list | grep {target gem name}` command.
It looks like that "rubocop-rake" and "rubocop-thread_safety" are not required on the .rubocop.yml. I wonder why the gems updated. Are not there the gems in your Gemfile?

> 2. The update feature should be removed or made optional, since the normal user does not use this gem to update gems, but to improve .rubocop_todo.yml. (This is the main reason I finally decided not to use rubocop_challenger in this project)

OK. It maybe consider to be made optional but not remove the feature.
I wrote the reason in the following blog: https://ryz310.hateblo.jp/entry/2021/09/24/113000

> 3. Installing all the gems used in the application is very time consuming, so it should only install the gems necessary to run RuboCop. (as a workaround, I created rubocop gem group and set BUNDLE_WITHOUT=default,development,test,production)

I see. Rubocop challenger are designed to run on nightly jobs. So it is not considering time consuming.
Your huck is very smart!

**Comment by r7kamura** [comment]
> > 1. The target gems should not be determined arbitrarily, but rather based on which libraries are used in the application.
> 
> Rubocop challenger does not determine target gems arbitrarily, it verifies that target gems have been installed with `$ bundle list | grep {target gem name}` command. It looks like that "rubocop-rake" and "rubocop-thread_safety" are not required on the .rubocop.yml. I wonder why the gems updated. Are not there the gems in your Gemfile?

Thanks for your reply.
I just didn't know the details and maybe I was wrong about this. Maybe these gems was updated based on the dependencies because it doesn't have `--conservative` option on `bundle update`. I will do some more investigation on this.

**Comment by r7kamura** [comment]
Now that I am convinced, and I know that there is no possibility of unrelated gems being installed (I didn't know that they are checked by `bundle list`, thx), so I'll close this issue 😃
