### ISSUE TITLE
Prevent duplicates

### ISSUE THREAD

**Issue by mathieujobin** [ryz310/rubocop_challenger#636]
**Describe the bug**
When we don't merge the PR, or let the repo unsupervised, new PR gets added every other day with the same changes.
Could rubocop_challenger check if the PR is already open, and either open a PR fixing a different rule automatically, that would be best.
or do nothing if that's simpler first step.

**Error information**
N/A

**RubocopChallenger version (please complete the following information):**
 - 2.7.0

**RuboCop versions (please complete the following information):**
```
$ grep '^    rubocop' Gemfile.lock 
    rubocop (1.30.1)
    rubocop-ast (1.18.0)
    rubocop-performance (1.14.2)
    rubocop-rails (2.14.2)
    rubocop-rake (0.6.0)
    rubocop-rspec (2.11.1)
    rubocop-thread_safety (0.4.4)
    rubocop_challenger (2.7.0)
```

**Additional context**
To many things to do... want to reduce noise and duplicate stuff

**Comment by ryz310** [comment]
Hi, @mathieujobin 

Hmm... I think this is not a bug, but an operational issue.
You can reduce rubocop challenge execution frequency. If you want to open a PR fixing a different rule, you can use a random mode that:

```rb
rubocop_challenger go \
  --email=email@example.com \
  --name=your_name \
  --mode=random
```

But I also want to prevent duplicates. Please see #205.
I will try. Thank you.

**Comment by mathieujobin** [comment]
Thank you for the suggestion of using `--mode=random` I think that will help a lot

I will close this since this is duplicate of #205
